name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@yarn-global-install
  # Since the Windows unit tests take much longer, we run the linux unit tests first and then run the windows unit tests in parallel with NUTs
  linux-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@yarn-global-install
    with:
      windows: false
  windows-unit-tests:
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@yarn-global-install
    with:
      linux: false
  nuts:
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@yarn-global-install
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-20-8core, windows-2022-16core]
        command:
          - 'yarn test:nuts:convert'
          - 'yarn test:nuts:commands:other'
          - 'yarn test:nuts:delete'
          - 'yarn test:nuts:deploy'
          - 'yarn test:nuts:deploy:async'
          - 'yarn test:nuts:deploy:rest'
          - 'yarn test:nuts:manifest:create'
          - 'yarn test:nuts:retrieve'
          - 'yarn test:nuts:specialTypes'
          - 'yarn test:nuts:deploy:destructive'
          - 'yarn test:nuts:tracking'
          - 'yarn test:nuts:mdapi'
      fail-fast: false
    with:
      os: ${{ matrix.os }}
      command: ${{ matrix.command }}
