name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  nuts:
    needs: unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-20-8core, windows-2022-16core]
        command:
          - 'yarn test:nuts:convert'
          - 'yarn test:nuts:commands:other'
          - 'yarn test:nuts:delete'
          - 'yarn test:nuts:deploy'
          - 'yarn test:nuts:deploy:async'
          - 'yarn test:nuts:deploy:rest'
          - 'yarn test:nuts:manifest:create'
          - 'yarn test:nuts:retrieve'
          - 'yarn test:nuts:specialTypes'
          - 'yarn test:nuts:deploy:destructive'
          - 'yarn test:nuts:tracking'
          - 'yarn test:nuts:mdapi'
      fail-fast: false
    with:
      os: ${{ matrix.os }}
      command: ${{ matrix.command }}
